In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
# Load the data
df = pd.read_csv('Obesity_prediction.csv')
df

Gender        Age    Height      Weight family_history FAVC  FCVC  NCP  \
0     Female  21.000000  1.620000   64.000000            yes   no   2.0  3.0   
1     Female  21.000000  1.520000   56.000000            yes   no   3.0  3.0   
2       Male  23.000000  1.800000   77.000000            yes   no   2.0  3.0   
3       Male  27.000000  1.800000   87.000000             no   no   3.0  3.0   
4       Male  22.000000  1.780000   89.800000             no   no   2.0  1.0   
...      ...        ...       ...         ...            ...  ...   ...  ...   
2106  Female  20.976842  1.710730  131.408528            yes  yes   3.0  3.0   
2107  Female  21.982942  1.748584  133.742943            yes  yes   3.0  3.0   
2108  Female  22.524036  1.752206  133.689352            yes  yes   3.0  3.0   
2109  Female  24.361936  1.739450  133.346641            yes  yes   3.0  3.0   
2110  Female  23.664709  1.738836  133.472641            yes  yes   3.0  3.0   

           CAEC SMOKE      CH2O  SCC       FAF       TUE        CALC  \
0     Sometimes    no  2.000000   no  0.000000  1.000000          no   
1     Sometimes   yes  3.000000  yes  3.000000  0.000000   Sometimes   
2     Sometimes    no  2.000000   no  2.000000  1.000000  Frequently   
3     Sometimes    no  2.000000   no  2.000000  0.000000  Frequently   
4     Sometimes    no  2.000000   no  0.000000  0.000000   Sometimes   
...         ...   ...       ...  ...       ...       ...         ...   
2106  Sometimes    no  1.728139   no  1.676269  0.906247   Sometimes   
2107  Sometimes    no  2.005130   no  1.341390  0.599270   Sometimes   
2108  Sometimes    no  2.054193   no  1.414209  0.646288   Sometimes   
2109  Sometimes    no  2.852339   no  1.139107  0.586035   Sometimes   
2110  Sometimes    no  2.863513   no  1.026452  0.714137   Sometimes   

                     MTRANS              Obesity  
0     Public_Transportation        Normal_Weight  
1     Public_Transportation        Normal_Weight  
2     Public_Transportation        Normal_Weight  
3                   Walking   Overweight_Level_I  
4     Public_Transportation  Overweight_Level_II  
...                     ...                  ...  
2106  Public_Transportation     Obesity_Type_III  
2107  Public_Transportation     Obesity_Type_III  
2108  Public_Transportation     Obesity_Type_III  
2109  Public_Transportation     Obesity_Type_III  
2110  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [21]:
df.sample(5)

Gender        Age    Height      Weight family_history FAVC      FCVC  \
840     Male  19.895877  1.807330   85.073801            yes  yes  2.801514   
1054    Male  30.553097  1.780448   88.431954            yes  yes  2.000000   
14      Male  23.000000  1.770000   60.000000            yes  yes  3.000000   
1918  Female  21.238416  1.763847  133.937873            yes  yes  3.000000   
201   Female  41.000000  1.540000   80.000000            yes  yes  2.000000   

           NCP       CAEC SMOKE      CH2O SCC       FAF       TUE       CALC  \
840   3.000000  Sometimes    no  2.734782  no  2.207881  0.143675  Sometimes   
1054  1.178708  Sometimes    no  1.791286  no  0.893362  0.276364  Sometimes   
14    1.000000  Sometimes    no  1.000000  no  1.000000  1.000000  Sometimes   
1918  3.000000  Sometimes    no  2.836791  no  1.467820  0.890527  Sometimes   
201   3.000000     Always    no  1.000000  no  0.000000  0.000000  Sometimes   

                     MTRANS              Obesity  
840   Public_Transportation   Overweight_Level_I  
1054  Public_Transportation  Overweight_Level_II  
14    Public_Transportation        Normal_Weight  
1918  Public_Transportation     Obesity_Type_III  
201              Automobile       Obesity_Type_I

In [22]:
df.dtypes

Gender             object
Age               float64
Height            float64
Weight            float64
family_history     object
FAVC               object
FCVC              float64
NCP               float64
CAEC               object
SMOKE              object
CH2O              float64
SCC                object
FAF               float64
TUE               float64
CALC               object
MTRANS             object
Obesity            object
dtype: object

In [23]:
df.isnull().sum()

Gender            0
Age               0
Height            0
Weight            0
family_history    0
FAVC              0
FCVC              0
NCP               0
CAEC              0
SMOKE             0
CH2O              0
SCC               0
FAF               0
TUE               0
CALC              0
MTRANS            0
Obesity           0
dtype: int64

In [24]:
df['SCC'].value_counts()

SCC
no     2015
yes      96
Name: count, dtype: int64

In [25]:
# Drop the TUE column
df = df.drop(columns=['TUE'])

# Check the DataFrame after dropping the column
print(df.head())

   Gender   Age  Height  Weight family_history FAVC  FCVC  NCP       CAEC  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0  Sometimes   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0  Sometimes   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0  Sometimes   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0  Sometimes   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0  Sometimes   

  SMOKE  CH2O  SCC  FAF        CALC                 MTRANS  \
0    no   2.0   no  0.0          no  Public_Transportation   
1   yes   3.0  yes  3.0   Sometimes  Public_Transportation   
2    no   2.0   no  2.0  Frequently  Public_Transportation   
3    no   2.0   no  2.0  Frequently                Walking   
4    no   2.0   no  0.0   Sometimes  Public_Transportation   

               Obesity  
0        Normal_Weight  
1        Normal_Weight  
2        Normal_Weight  
3   Overweight_Level_I  
4  Overweight_Level_II  


In [26]:
# One hot encoding for CAEC, CALC, MTRANS
df = pd.get_dummies(df, columns=['CAEC', 'CALC','MTRANS'])

df.head()

Gender   Age  Height  Weight family_history FAVC  FCVC  NCP SMOKE  CH2O  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0    no   2.0   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0   yes   3.0   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0    no   2.0   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0    no   2.0   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0    no   2.0   

   ... CAEC_no  CALC_Always CALC_Frequently  CALC_Sometimes  CALC_no  \
0  ...   False        False           False           False     True   
1  ...   False        False           False            True    False   
2  ...   False        False            True           False    False   
3  ...   False        False            True           False    False   
4  ...   False        False           False            True    False   

   MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
0              False        False             False   
1              False        False             False   
2              False        False             False   
3              False        False             False   
4              False        False             False   

   MTRANS_Public_Transportation  MTRANS_Walking  
0                          True           False  
1                          True           False  
2                          True           False  
3                         False            True  
4                          True           False  

[5 rows x 26 columns]

In [27]:
# rounding age
df['Age'] = df['Age'].round()

#GENDER (binary)
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

#SMOKE (binary)
df['SMOKE'] = df['SMOKE'].map({'yes': 1, 'no': 0})

#family_history (binary)
df['family_history'] = df['family_history'].map({'yes': 1, 'no': 0})

#FAVC (binary)
df['FAVC'] = df['FAVC'].map({'yes': 1, 'no': 0})

#SCC
df['SCC'] = df['SCC'].map({'yes': 1, 'no': 0})

df.sample(10)


Gender   Age    Height      Weight  family_history  FAVC      FCVC  \
1467       1  18.0  1.806827  108.829395               1     1  2.000000   
252        1  56.0  1.790000   90.000000               1     0  2.000000   
1918       0  21.0  1.763847  133.937873               1     1  3.000000   
1678       1  31.0  1.868127  123.172214               1     1  2.585942   
2091       0  26.0  1.640535  111.555967               1     1  3.000000   
1171       0  38.0  1.676095   79.079738               1     1  2.802128   
386        0  18.0  1.590000   53.000000               0     0  1.000000   
1428       1  22.0  1.741393   98.182498               1     1  2.000000   
786        0  24.0  1.588597   62.339003               0     1  2.397280   
129        1  27.0  1.700000   78.000000               0     1  3.000000   

           NCP  SMOKE      CH2O  ...  CAEC_no  CALC_Always CALC_Frequently  \
1467  1.248840      0  2.416213  ...    False        False           False   
252   3.000000      1  2.000000  ...    False        False            True   
1918  3.000000      0  2.836791  ...    False        False           False   
1678  3.000000      0  2.302506  ...    False        False           False   
2091  3.000000      0  2.634342  ...    False        False           False   
1171  3.000000      0  1.744628  ...    False        False           False   
386   3.000000      0  1.000000  ...    False        False           False   
1428  2.978103      0  2.668261  ...    False        False           False   
786   2.656588      0  2.061062  ...    False        False           False   
129   3.000000      0  3.000000  ...    False        False            True   

      CALC_Sometimes  CALC_no  MTRANS_Automobile  MTRANS_Bike  \
1467           False     True              False        False   
252            False    False               True        False   
1918            True    False              False        False   
1678            True    False              False        False   
2091            True    False              False        False   
1171           False     True               True        False   
386            False     True              False        False   
1428           False     True              False        False   
786             True    False              False        False   
129            False    False              False        False   

      MTRANS_Motorbike  MTRANS_Public_Transportation  MTRANS_Walking  
1467             False                          True           False  
252              False                         False           False  
1918             False                          True           False  
1678             False                          True           False  
2091             False                          True           False  
1171             False                         False           False  
386              False                          True           False  
1428             False                          True           False  
786              False                          True           False  
129              False                          True           False  

[10 rows x 26 columns]

In [28]:
# calculating of the BMI
df['BMI'] = df['Weight'] / (df['Height'] ** 2)

print(df[['Height', 'Weight', 'BMI']].head())

   Height  Weight        BMI
0    1.62    64.0  24.386526
1    1.52    56.0  24.238227
2    1.80    77.0  23.765432
3    1.80    87.0  26.851852
4    1.78    89.8  28.342381


In [29]:
# after getting BMI can drop weight and height
df = df.drop(columns=['Weight', 'Height'])

print(df.head())

   Gender   Age  family_history  FAVC  FCVC  NCP  SMOKE  CH2O  SCC  FAF  ...  \
0       0  21.0               1     0   2.0  3.0      0   2.0    0  0.0  ...   
1       0  21.0               1     0   3.0  3.0      1   3.0    1  3.0  ...   
2       1  23.0               1     0   2.0  3.0      0   2.0    0  2.0  ...   
3       1  27.0               0     0   3.0  3.0      0   2.0    0  2.0  ...   
4       1  22.0               0     0   2.0  1.0      0   2.0    0  0.0  ...   

  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  MTRANS_Automobile  \
0       False            False           False     True              False   
1       False            False            True    False              False   
2       False             True           False    False              False   
3       False             True           False    False              False   
4       False            False            True    False              False   

   MTRANS_Bike  MTRANS_Motorbike  MTRANS_Public_Tr

In [30]:
df[df.columns].value_counts()

Gender  Age   family_history  FAVC  FCVC      NCP       SMOKE  CH2O      SCC  FAF       Obesity              CAEC_Always  CAEC_Frequently  CAEC_Sometimes  CAEC_no  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  MTRANS_Public_Transportation  MTRANS_Walking  BMI      
1       21.0  0               1     2.000000  1.000000  0      3.000000  0    1.000000  Overweight_Level_I   False        False            False           True     False        False            True            False    False              False        False             True                          False           26.672763    15
0       21.0  0               1     3.000000  1.000000  0      1.000000  0    0.000000  Insufficient_Weight  False        True             False           False    False        False            True            False    False              False        False             True                          False           18.178670     4
        22.0 

In [31]:
#Obesity column to numeric values
obesity_mapping = {
    'Insufficient_Weight': 0,
    'Normal_Weight': 1,
    'Overweight_Level_I': 2,
    'Overweight_Level_II': 3,
    'Obesity_Type_I': 4,
    'Obesity_Type_II': 5,
    'Obesity_Type_III': 6
}

# apply the mapping to the Obesity column
df['Obesity'] = df['Obesity'].map(obesity_mapping)


df.sample(10)

Gender   Age  family_history  FAVC      FCVC       NCP  SMOKE      CH2O  \
2036       0  26.0               1     1  3.000000  3.000000      0  2.419153   
1152       1  23.0               1     1  1.963965  1.836226      0  1.855370   
295        0  16.0               0     0  2.000000  1.000000      0  1.000000   
716        1  17.0               1     1  2.883745  3.595761      0  2.000000   
40         0  21.0               1     1  2.000000  3.000000      0  2.000000   
762        1  23.0               0     1  2.000000  1.000000      0  2.803311   
2048       0  19.0               1     1  3.000000  3.000000      0  1.144539   
1895       0  26.0               1     1  3.000000  3.000000      0  1.000544   
2003       0  26.0               1     1  3.000000  3.000000      0  2.619517   
1823       0  26.0               1     1  3.000000  3.000000      0  1.003563   

      SCC       FAF  ...  CALC_Always  CALC_Frequently  CALC_Sometimes  \
2036    0  0.019404  ...        False            False            True   
1152    0  0.000000  ...        False            False            True   
295     0  0.000000  ...        False            False           False   
716     0  2.077653  ...        False            False           False   
40      0  1.000000  ...        False            False            True   
762     0  0.245354  ...        False            False            True   
2048    0  0.922014  ...        False            False            True   
1895    0  0.001297  ...        False            False            True   
2003    0  0.000000  ...        False            False            True   
1823    0  0.008127  ...        False            False            True   

      CALC_no  MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
2036    False              False        False             False   
1152    False              False        False             False   
295      True              False        False             False   
716      True               True        False             False   
40      False              False        False             False   
762     False              False        False             False   
2048    False              False        False             False   
1895    False              False        False             False   
2003    False              False        False             False   
1823    False              False        False             False   

      MTRANS_Public_Transportation  MTRANS_Walking        BMI  
2036                          True           False  39.144682  
1152                          True           False  27.941209  
295                          False            True  21.048048  
716                          False           False  17.357415  
40                            True           False  26.892323  
762                           True           False  26.372569  
2048                          True           False  45.245762  
1895                          True           False  41.457951  
2003                          True           False  41.946035  
1823                          True           False  40.810169  

[10 rows x 25 columns]

In [32]:
X = df.drop(columns=['Obesity'])  # Drop Obesity
y = df['Obesity']


In [33]:
#Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#Random Forest model
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [34]:
# importance
importances = rf_model.feature_importances_

# numpy array
feature_importance_array = np.array(importances)

# Sort them
sorted_feature_indexes = feature_importance_array.argsort()[::-1]  # Reverse to get from most to least important

sorted_feature_importance_df = pd.DataFrame({
    'Feature': X.columns[sorted_feature_indexes], 
    'Importance': feature_importance_array[sorted_feature_indexes] 
})

# Print each feature and its importance using a for loop
for index in sorted_feature_indexes:
    print("({}): {:.2f}%".format(X.columns[index], (feature_importance_array[index] * 100)))

(BMI): 41.00%
(Age): 8.84%
(FCVC): 8.75%
(NCP): 5.96%
(CH2O): 5.54%
(FAF): 5.52%
(Gender): 5.00%
(family_history): 3.45%
(CALC_Sometimes): 2.25%
(CAEC_Sometimes): 2.25%
(CALC_no): 2.05%
(CAEC_Frequently): 1.70%
(FAVC): 1.68%
(MTRANS_Automobile): 1.61%
(MTRANS_Public_Transportation): 1.51%
(SCC): 0.76%
(CAEC_no): 0.51%
(MTRANS_Walking): 0.45%
(CALC_Frequently): 0.42%
(CAEC_Always): 0.33%
(SMOKE): 0.28%
(MTRANS_Bike): 0.08%
(MTRANS_Motorbike): 0.06%
(CALC_Always): 0.00%


In [35]:
# Drop column
df = df.drop(columns=['SCC', 'CALC_Always', 'CALC_Frequently','CALC_no','CALC_Sometimes','MTRANS_Motorbike','MTRANS_Bike','MTRANS_Walking','MTRANS_Public_Transportation','MTRANS_Automobile','SMOKE','CAEC_Always','CAEC_no','CAEC_Frequently','CAEC_Sometimes','SCC','FAVC'])
print(df.head())

   Gender   Age  family_history  FCVC  NCP  CH2O  FAF  Obesity        BMI
0       0  21.0               1   2.0  3.0   2.0  0.0        1  24.386526
1       0  21.0               1   3.0  3.0   3.0  3.0        1  24.238227
2       1  23.0               1   2.0  3.0   2.0  2.0        1  23.765432
3       1  27.0               0   3.0  3.0   2.0  2.0        2  26.851852
4       1  22.0               0   2.0  1.0   2.0  0.0        3  28.342381


In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Create the model
model = RandomForestClassifier(random_state=42)

# Grid search
param_grid = {
   'n_estimators': [50, 100, 200],
   'max_depth': [3, 5, 7, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get best model
best_model = grid_search.best_estimator_

# Evaluate on test set
y_pred = best_model.predict(X_test)
print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.2f}")

Test Accuracy: 0.96


In [37]:
# Retrain test accuracy
threshold = 0.01
important_features = sorted_feature_importance_df[sorted_feature_importance_df['Importance'] > threshold]['Feature']

X_train_important = X_train[important_features]
X_test_important = X_test[important_features]

rf_model = RandomForestClassifier(random_state=42)

# Set up the parameter grid for grid search
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# grid search
grid_search = GridSearchCV(rf_model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_important, y_train)

# get the best model from the grid search
best_rf_model = grid_search.best_estimator_

# evaluate the best model
y_pred_retrained = best_rf_model.predict(X_test_important)
print(f"Retrained Test Accuracy: {accuracy_score(y_test, y_pred_retrained):.2f}")


Retrained Test Accuracy: 0.97


In [38]:
# Define parameter grid
from sklearn.tree import DecisionTreeClassifier


# Define parameter grid
param_grid = {
   'max_depth': [3, 5, 7, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4],
   'criterion': ['gini', 'entropy']
}

# Create GridSearchCV object
grid_search = GridSearchCV(
   estimator=DecisionTreeClassifier(random_state=42),
   param_grid=param_grid,
   cv=5,
   scoring='accuracy',
   n_jobs=-1
)

# Perform grid search
grid_search.fit(X_train, y_train)

# Get best model
dt_model = grid_search.best_estimator_

# Make predictions
y_pred = dt_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))

Test Accuracy: 0.9637223974763407


In [39]:
threshold = 0.01 
important_features = sorted_feature_importance_df[sorted_feature_importance_df['Importance'] > threshold]['Feature']


X_train_important = X_train[important_features]
X_test_important = X_test[important_features]

param_grid = {
   'max_depth': [3, 5, 7, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4],
   'criterion': ['gini', 'entropy']
}

grid_search = GridSearchCV(
   estimator=DecisionTreeClassifier(random_state=42),
   param_grid=param_grid,
   cv=5,
   scoring='accuracy',
   n_jobs=-1
)

grid_search.fit(X_train_important, y_train)

# Get best model from grid search
dt_model_retrained = grid_search.best_estimator_

y_pred_retrained = dt_model_retrained.predict(X_test_important)

# Print retrained accuracy
print("Retrained Test Accuracy:", accuracy_score(y_test, y_pred_retrained))


Retrained Test Accuracy: 0.973186119873817


In [40]:
from sklearn.metrics import confusion_matrix, classification_report

# Generate and print the confusion matrix
print("Confusion matrix:")
conf_matrix = confusion_matrix(y_test, y_pred_retrained)
print(conf_matrix)

# Print the classification report
print("Classification report:")
print(classification_report(y_test, y_pred_retrained))


Confusion matrix:
[[84  2  0  0  0  0  0]
 [ 0 92  1  0  0  0  0]
 [ 0  2 83  3  0  0  0]
 [ 0  0  0 78  1  0  0]
 [ 0  0  0  1 96  4  1]
 [ 0  0  0  0  1 87  0]
 [ 0  0  0  0  0  1 97]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        86
           1       0.96      0.99      0.97        93
           2       0.99      0.94      0.97        88
           3       0.95      0.99      0.97        79
           4       0.98      0.94      0.96       102
           5       0.95      0.99      0.97        88
           6       0.99      0.99      0.99        98

    accuracy                           0.97       634
   macro avg       0.97      0.97      0.97       634
weighted avg       0.97      0.97      0.97       634



In [41]:
# Save the best Decision Tree retrained model
import joblib

joblib.dump(dt_model_retrained, 'obesity_decision_tree_retrained_model.pkl')

# Optional: Verify the saved retrained model
loaded_retrained_model = joblib.load('obesity_decision_tree_retrained_model.pkl')

# Confirm model performance remains the same on the important features
loaded_retrained_predictions = loaded_retrained_model.predict(X_test_important)
print("Retrained Model Accuracy:", accuracy_score(y_test, loaded_retrained_predictions))

Retrained Model Accuracy: 0.973186119873817
