In [292]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

In [320]:
# Load the data
df = pd.read_csv('Obesity_prediction.csv')
df

Gender        Age    Height      Weight family_history FAVC  FCVC  NCP  \
0     Female  21.000000  1.620000   64.000000            yes   no   2.0  3.0   
1     Female  21.000000  1.520000   56.000000            yes   no   3.0  3.0   
2       Male  23.000000  1.800000   77.000000            yes   no   2.0  3.0   
3       Male  27.000000  1.800000   87.000000             no   no   3.0  3.0   
4       Male  22.000000  1.780000   89.800000             no   no   2.0  1.0   
...      ...        ...       ...         ...            ...  ...   ...  ...   
2106  Female  20.976842  1.710730  131.408528            yes  yes   3.0  3.0   
2107  Female  21.982942  1.748584  133.742943            yes  yes   3.0  3.0   
2108  Female  22.524036  1.752206  133.689352            yes  yes   3.0  3.0   
2109  Female  24.361936  1.739450  133.346641            yes  yes   3.0  3.0   
2110  Female  23.664709  1.738836  133.472641            yes  yes   3.0  3.0   

           CAEC SMOKE      CH2O  SCC       FAF       TUE        CALC  \
0     Sometimes    no  2.000000   no  0.000000  1.000000          no   
1     Sometimes   yes  3.000000  yes  3.000000  0.000000   Sometimes   
2     Sometimes    no  2.000000   no  2.000000  1.000000  Frequently   
3     Sometimes    no  2.000000   no  2.000000  0.000000  Frequently   
4     Sometimes    no  2.000000   no  0.000000  0.000000   Sometimes   
...         ...   ...       ...  ...       ...       ...         ...   
2106  Sometimes    no  1.728139   no  1.676269  0.906247   Sometimes   
2107  Sometimes    no  2.005130   no  1.341390  0.599270   Sometimes   
2108  Sometimes    no  2.054193   no  1.414209  0.646288   Sometimes   
2109  Sometimes    no  2.852339   no  1.139107  0.586035   Sometimes   
2110  Sometimes    no  2.863513   no  1.026452  0.714137   Sometimes   

                     MTRANS              Obesity  
0     Public_Transportation        Normal_Weight  
1     Public_Transportation        Normal_Weight  
2     Public_Transportation        Normal_Weight  
3                   Walking   Overweight_Level_I  
4     Public_Transportation  Overweight_Level_II  
...                     ...                  ...  
2106  Public_Transportation     Obesity_Type_III  
2107  Public_Transportation     Obesity_Type_III  
2108  Public_Transportation     Obesity_Type_III  
2109  Public_Transportation     Obesity_Type_III  
2110  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [294]:
df.sample(5)

Gender        Age    Height      Weight family_history FAVC  FCVC  \
980     Male  21.183540  1.720000   80.555875            yes  yes   2.0   
1485    Male  18.611197  1.714143   96.568814            yes  yes   2.0   
1807  Female  22.392510  1.655630  121.205171            yes  yes   3.0   
209   Female  22.000000  1.690000   65.000000            yes  yes   2.0   
2024  Female  20.323767  1.774207  138.143162            yes  yes   3.0   

           NCP       CAEC SMOKE      CH2O SCC       FAF       TUE       CALC  \
980   2.468421  Sometimes    no  2.000000  no  2.000000  1.000000         no   
1485  2.967089  Sometimes    no  2.000000  no  0.000000  0.467048         no   
1807  3.000000  Sometimes    no  1.347559  no  0.462951  0.317940  Sometimes   
209   3.000000  Sometimes    no  2.000000  no  1.000000  1.000000  Sometimes   
2024  3.000000  Sometimes    no  2.816052  no  1.571865  0.688058  Sometimes   

                     MTRANS              Obesity  
980   Public_Transportation  Overweight_Level_II  
1485  Public_Transportation       Obesity_Type_I  
1807  Public_Transportation     Obesity_Type_III  
209   Public_Transportation        Normal_Weight  
2024  Public_Transportation     Obesity_Type_III

In [295]:
df.dtypes

Gender             object
Age               float64
Height            float64
Weight            float64
family_history     object
FAVC               object
FCVC              float64
NCP               float64
CAEC               object
SMOKE              object
CH2O              float64
SCC                object
FAF               float64
TUE               float64
CALC               object
MTRANS             object
Obesity            object
dtype: object

In [296]:
df.isnull().sum()

Gender            0
Age               0
Height            0
Weight            0
family_history    0
FAVC              0
FCVC              0
NCP               0
CAEC              0
SMOKE             0
CH2O              0
SCC               0
FAF               0
TUE               0
CALC              0
MTRANS            0
Obesity           0
dtype: int64

In [297]:
df['SCC'].value_counts()

SCC
no     2015
yes      96
Name: count, dtype: int64

In [298]:
# Drop the TUE column
df = df.drop(columns=['TUE'])

# Check the DataFrame after dropping the column
print(df.head())

   Gender   Age  Height  Weight family_history FAVC  FCVC  NCP       CAEC  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0  Sometimes   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0  Sometimes   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0  Sometimes   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0  Sometimes   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0  Sometimes   

  SMOKE  CH2O  SCC  FAF        CALC                 MTRANS  \
0    no   2.0   no  0.0          no  Public_Transportation   
1   yes   3.0  yes  3.0   Sometimes  Public_Transportation   
2    no   2.0   no  2.0  Frequently  Public_Transportation   
3    no   2.0   no  2.0  Frequently                Walking   
4    no   2.0   no  0.0   Sometimes  Public_Transportation   

               Obesity  
0        Normal_Weight  
1        Normal_Weight  
2        Normal_Weight  
3   Overweight_Level_I  
4  Overweight_Level_II  


In [299]:
# One hot encoding for CAEC, CALC, MTRANS
df = pd.get_dummies(df, columns=['CAEC', 'CALC','MTRANS'])

df.head()

Gender   Age  Height  Weight family_history FAVC  FCVC  NCP SMOKE  CH2O  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0    no   2.0   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0   yes   3.0   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0    no   2.0   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0    no   2.0   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0    no   2.0   

   ... CAEC_no  CALC_Always CALC_Frequently  CALC_Sometimes  CALC_no  \
0  ...   False        False           False           False     True   
1  ...   False        False           False            True    False   
2  ...   False        False            True           False    False   
3  ...   False        False            True           False    False   
4  ...   False        False           False            True    False   

   MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
0              False        False             False   
1              False        False             False   
2              False        False             False   
3              False        False             False   
4              False        False             False   

   MTRANS_Public_Transportation  MTRANS_Walking  
0                          True           False  
1                          True           False  
2                          True           False  
3                         False            True  
4                          True           False  

[5 rows x 26 columns]

In [300]:
# rounding age
df['Age'] = df['Age'].round()

#GENDER (binary)
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

#SMOKE (binary)
df['SMOKE'] = df['SMOKE'].map({'yes': 1, 'no': 0})

#family_history (binary)
df['family_history'] = df['family_history'].map({'yes': 1, 'no': 0})

#FAVC (binary)
df['FAVC'] = df['FAVC'].map({'yes': 1, 'no': 0})

#SCC
df['SCC'] = df['SCC'].map({'yes': 1, 'no': 0})

df.sample(10)


Gender   Age    Height      Weight  family_history  FAVC      FCVC  \
1654       1  25.0  1.769933  117.708705               1     1  1.475906   
759        0  35.0  1.529834   62.903938               0     1  2.000000   
2038       0  26.0  1.608283  105.359688               1     1  3.000000   
1829       0  26.0  1.669701  104.585783               1     1  3.000000   
267        1  38.0  1.700000   78.000000               0     1  3.000000   
1760       1  31.0  1.773521  120.209711               1     1  2.777165   
944        1  26.0  1.767806   82.694689               1     1  1.947405   
799        0  19.0  1.760000   79.544998               1     1  2.000000   
106        0  25.0  1.570000   55.000000               0     1  2.000000   
1572       1  29.0  1.815347  120.399758               1     1  2.967300   

           NCP  SMOKE      CH2O  ...  CAEC_no  CALC_Always CALC_Frequently  \
1654  2.999346      0  2.019430  ...    False        False           False   
759   2.105616      0  1.456581  ...    False        False           False   
2038  3.000000      0  2.476002  ...    False        False           False   
1829  3.000000      0  1.570188  ...    False        False           False   
267   3.000000      0  2.000000  ...    False        False            True   
1760  3.000000      0  2.106861  ...    False        False           False   
944   3.118013      0  2.136159  ...    False        False           False   
799   1.146794      0  3.000000  ...    False        False            True   
106   1.000000      0  2.000000  ...    False        False           False   
1572  3.000000      0  2.530035  ...    False        False           False   

      CALC_Sometimes  CALC_no  MTRANS_Automobile  MTRANS_Bike  \
1654            True    False              False        False   
759             True    False               True        False   
2038            True    False              False        False   
1829            True    False              False        False   
267            False    False               True        False   
1760            True    False               True        False   
944            False     True              False        False   
799            False    False              False        False   
106             True    False              False        False   
1572            True    False               True        False   

      MTRANS_Motorbike  MTRANS_Public_Transportation  MTRANS_Walking  
1654             False                          True           False  
759              False                         False           False  
2038             False                          True           False  
1829             False                          True           False  
267              False                         False           False  
1760             False                         False           False  
944              False                          True           False  
799              False                          True           False  
106              False                          True           False  
1572             False                         False           False  

[10 rows x 26 columns]

In [301]:
# calculating of the BMI
df['BMI'] = df['Weight'] / (df['Height'] ** 2)

print(df[['Height', 'Weight', 'BMI']].head())

   Height  Weight        BMI
0    1.62    64.0  24.386526
1    1.52    56.0  24.238227
2    1.80    77.0  23.765432
3    1.80    87.0  26.851852
4    1.78    89.8  28.342381


In [302]:
# after getting BMI can drop weight and height
df = df.drop(columns=['Weight', 'Height'])

print(df.head())

   Gender   Age  family_history  FAVC  FCVC  NCP  SMOKE  CH2O  SCC  FAF  ...  \
0       0  21.0               1     0   2.0  3.0      0   2.0    0  0.0  ...   
1       0  21.0               1     0   3.0  3.0      1   3.0    1  3.0  ...   
2       1  23.0               1     0   2.0  3.0      0   2.0    0  2.0  ...   
3       1  27.0               0     0   3.0  3.0      0   2.0    0  2.0  ...   
4       1  22.0               0     0   2.0  1.0      0   2.0    0  0.0  ...   

  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  MTRANS_Automobile  \
0       False            False           False     True              False   
1       False            False            True    False              False   
2       False             True           False    False              False   
3       False             True           False    False              False   
4       False            False            True    False              False   

   MTRANS_Bike  MTRANS_Motorbike  MTRANS_Public_Tr

In [303]:
df[df.columns].value_counts()

Gender  Age   family_history  FAVC  FCVC      NCP       SMOKE  CH2O      SCC  FAF       Obesity              CAEC_Always  CAEC_Frequently  CAEC_Sometimes  CAEC_no  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  MTRANS_Public_Transportation  MTRANS_Walking  BMI      
1       21.0  0               1     2.000000  1.000000  0      3.000000  0    1.000000  Overweight_Level_I   False        False            False           True     False        False            True            False    False              False        False             True                          False           26.672763    15
0       21.0  0               1     3.000000  1.000000  0      1.000000  0    0.000000  Insufficient_Weight  False        True             False           False    False        False            True            False    False              False        False             True                          False           18.178670     4
        22.0 

In [304]:
#Obesity column to numeric values
obesity_mapping = {
    'Insufficient_Weight': 0,
    'Normal_Weight': 1,
    'Overweight_Level_I': 2,
    'Overweight_Level_II': 3,
    'Obesity_Type_I': 4,
    'Obesity_Type_II': 5,
    'Obesity_Type_III': 6
}

# apply the mapping to the Obesity column
df['Obesity'] = df['Obesity'].map(obesity_mapping)


df.sample(10)

Gender   Age  family_history  FAVC      FCVC       NCP  SMOKE      CH2O  \
1464       1  21.0               1     1  2.000000  3.000000      0  1.613829   
1644       1  27.0               1     1  2.765063  3.000000      0  2.867206   
418        1  18.0               0     1  3.000000  3.000000      0  2.000000   
2022       0  26.0               1     1  3.000000  3.000000      0  1.237557   
1176       0  19.0               1     0  3.000000  3.129155      0  2.000000   
1391       0  23.0               1     1  2.964419  1.000000      0  2.977516   
29         1  23.0               0     1  2.000000  3.000000      0  2.000000   
1659       1  23.0               1     1  3.000000  2.510135      0  1.693362   
1510       0  19.0               1     1  2.765330  3.000000      0  1.048584   
1608       1  39.0               1     1  2.702457  3.000000      0  2.005194   

      SCC       FAF  ...  CALC_Always  CALC_Frequently  CALC_Sometimes  \
1464    0  1.251665  ...        False            False            True   
1644    0  0.706777  ...        False            False            True   
418     0  2.000000  ...        False            False            True   
2022    0  0.083675  ...        False            False            True   
1176    0  1.634134  ...        False            False           False   
1391    0  0.742113  ...        False            False            True   
29      0  2.000000  ...        False             True           False   
1659    0  0.769709  ...        False            False            True   
1510    0  0.192559  ...        False            False           False   
1608    0  0.325313  ...        False            False            True   

      CALC_no  MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
1464    False              False        False             False   
1644    False              False        False             False   
418     False              False        False             False   
2022    False              False        False             False   
1176     True              False        False             False   
1391    False              False        False             False   
29      False              False        False             False   
1659    False              False        False             False   
1510     True              False        False             False   
1608    False               True        False             False   

      MTRANS_Public_Transportation  MTRANS_Walking        BMI  
1464                          True           False  32.454806  
1644                          True           False  35.436555  
418                           True           False  31.141869  
2022                          True           False  40.282771  
1176                          True           False  29.620572  
1391                          True           False  31.756843  
29                           False            True  24.801587  
1659                          True           False  35.573390  
1510                          True           False  31.828525  
1608                         False           False  38.866646  

[10 rows x 25 columns]

In [305]:
X = df.drop(columns=['Obesity'])  # Drop Obesity
y = df['Obesity']


In [306]:
#Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#Random Forest model
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [307]:
# importance
importances = rf_model.feature_importances_

# numpy array
feature_importance_array = np.array(importances)

# Sort them
sorted_feature_indexes = feature_importance_array.argsort()[::-1]  # Reverse to get from most to least important

sorted_feature_importance_df = pd.DataFrame({
    'Feature': X.columns[sorted_feature_indexes], 
    'Importance': feature_importance_array[sorted_feature_indexes] 
})

# Print each feature and its importance using a for loop
for index in sorted_feature_indexes:
    print("({}): {:.2f}%".format(X.columns[index], (feature_importance_array[index] * 100)))

(BMI): 41.00%
(Age): 8.84%
(FCVC): 8.75%
(NCP): 5.96%
(CH2O): 5.54%
(FAF): 5.52%
(Gender): 5.00%
(family_history): 3.45%
(CALC_Sometimes): 2.25%
(CAEC_Sometimes): 2.25%
(CALC_no): 2.05%
(CAEC_Frequently): 1.70%
(FAVC): 1.68%
(MTRANS_Automobile): 1.61%
(MTRANS_Public_Transportation): 1.51%
(SCC): 0.76%
(CAEC_no): 0.51%
(MTRANS_Walking): 0.45%
(CALC_Frequently): 0.42%
(CAEC_Always): 0.33%
(SMOKE): 0.28%
(MTRANS_Bike): 0.08%
(MTRANS_Motorbike): 0.06%
(CALC_Always): 0.00%


In [327]:
# Drop column
df = df.drop(columns=['SCC', 'CALC_Always', 'CALC_Frequently','CALC_no','CALC_Sometimes','MTRANS_Motorbike','MTRANS_Bike','MTRANS_Walking','MTRANS_Public_Transportation','MTRANS_Automobile','SMOKE','CAEC_Always','CAEC_no','CAEC_Frequently','CAEC_Sometimes','SCC','FAVC'])
print(df.head())

KeyError: "['CALC_Always', 'CALC_Frequently', 'CALC_no', 'CALC_Sometimes', 'MTRANS_Motorbike', 'MTRANS_Bike', 'MTRANS_Walking', 'MTRANS_Public_Transportation', 'MTRANS_Automobile', 'CAEC_Always', 'CAEC_no', 'CAEC_Frequently', 'CAEC_Sometimes'] not found in axis"

In [324]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Create the model
model = RandomForestClassifier(random_state=42)

# Grid search
param_grid = {
   'n_estimators': [50, 100, 200],
   'max_depth': [3, 5, 7, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get best model
best_model = grid_search.best_estimator_

# Evaluate on test set
y_pred = best_model.predict(X_test)
print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.2f}")

Test Accuracy: 0.96


In [ ]:
# Retrain test accuracy
threshold = 0.01
important_features = sorted_feature_importance_df[sorted_feature_importance_df['Importance'] > threshold]['Feature']

X_train_important = X_train[important_features]
X_test_important = X_test[important_features]

rf_model = RandomForestClassifier(random_state=42)

# Set up the parameter grid for grid search
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# grid search
grid_search = GridSearchCV(rf_model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_important, y_train)

# get the best model from the grid search
best_rf_model = grid_search.best_estimator_

# evaluate the best model
y_pred_retrained = best_rf_model.predict(X_test_important)
print(f"Retrained Test Accuracy: {accuracy_score(y_test, y_pred_retrained):.2f}")


Retrained Test Accuracy with Grid Search: 0.97


In [317]:
# Define parameter grid
from sklearn.tree import DecisionTreeClassifier


# Define parameter grid
param_grid = {
   'max_depth': [3, 5, 7, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4],
   'criterion': ['gini', 'entropy']
}

# Create GridSearchCV object
grid_search = GridSearchCV(
   estimator=DecisionTreeClassifier(random_state=42),
   param_grid=param_grid,
   cv=5,
   scoring='accuracy',
   n_jobs=-1
)

# Perform grid search
grid_search.fit(X_train, y_train)

# Get best model
dt_model = grid_search.best_estimator_

# Make predictions
y_pred = dt_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))

Test Accuracy: 0.9637223974763407


In [ ]:
threshold = 0.01 
important_features = sorted_feature_importance_df[sorted_feature_importance_df['Importance'] > threshold]['Feature']


X_train_important = X_train[important_features]
X_test_important = X_test[important_features]

param_grid = {
   'max_depth': [3, 5, 7, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4],
   'criterion': ['gini', 'entropy']
}

grid_search = GridSearchCV(
   estimator=DecisionTreeClassifier(random_state=42),
   param_grid=param_grid,
   cv=5,
   scoring='accuracy',
   n_jobs=-1
)

grid_search.fit(X_train_important, y_train)

# Get best model from grid search
dt_model_retrained = grid_search.best_estimator_

y_pred_retrained = dt_model_retrained.predict(X_test_important)

# Print retrained accuracy
print("Retrained Test Accuracy:", accuracy_score(y_test, y_pred_retrained))


Retrained Test Accuracy: 0.973186119873817


In [336]:
from sklearn.metrics import confusion_matrix, classification_report

# Generate and print the confusion matrix
print("Confusion matrix:")
conf_matrix = confusion_matrix(y_test, y_pred_retrained)
print(conf_matrix)

# Print the classification report
print("Classification report:")
print(classification_report(y_test, y_pred_retrained))


Confusion matrix:
[[84  2  0  0  0  0  0]
 [ 0 92  1  0  0  0  0]
 [ 0  2 83  3  0  0  0]
 [ 0  0  0 78  1  0  0]
 [ 0  0  0  1 96  4  1]
 [ 0  0  0  0  1 87  0]
 [ 0  0  0  0  0  1 97]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        86
           1       0.96      0.99      0.97        93
           2       0.99      0.94      0.97        88
           3       0.95      0.99      0.97        79
           4       0.98      0.94      0.96       102
           5       0.95      0.99      0.97        88
           6       0.99      0.99      0.99        98

    accuracy                           0.97       634
   macro avg       0.97      0.97      0.97       634
weighted avg       0.97      0.97      0.97       634



In [ ]:
# Save the best Decision Tree retrained model
import joblib

joblib.dump(dt_model_retrained, 'obesity_decision_tree_retrained_model.pkl')

# Optional: Verify the saved retrained model
loaded_retrained_model = joblib.load('obesity_decision_tree_retrained_model.pkl')

# Confirm model performance remains the same on the important features
loaded_retrained_predictions = loaded_retrained_model.predict(X_test_important)
print("Retrained Model Accuracy:", accuracy_score(y_test, loaded_retrained_predictions))

Retrained Model Accuracy: 0.973186119873817
